# Generated by Django 4.1.5 on 2023-02-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('surname', models.CharField(max_length=30, verbose_name='surname')),
                ('age', models.IntegerField(verbose_name='age')),
                ('sex', models.CharField(default='', max_length=1)),
                ('phone', models.IntegerField(verbose_name='Phone number')),
                ('msg', models.CharField(default='', max_length=100, verbose_name='MSG')),
                ('hobbies', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_friend.hobbies')),
            ],
        ),
    ]
