# Generated by Django 4.1.5 on 2023-02-11 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_friend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=40)),
                ('average_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='hobbies',
        ),
        migrations.AlterField(
            model_name='users',
            name='msg',
            field=models.CharField(max_length=100, verbose_name='MSG'),
        ),
        migrations.AddField(
            model_name='users',
            name='favorite_place_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_friend.cafe'),
        ),
        migrations.AddField(
            model_name='users',
            name='work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_friend.work'),
        ),
        migrations.AddField(
            model_name='users',
            name='hobbies',
            field=models.ManyToManyField(to='app_friend.hobbies', verbose_name='list of hobbies'),
        ),
    ]
