# Generated by Django 4.1.5 on 2023-02-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_friend', '0002_cafe_work_remove_users_hobbies_alter_users_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='pilot_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='work',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_friend.work'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['sex'], name='sex_idx'),
        ),
    ]
