# Generated by Django 4.1.5 on 2023-03-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_friend', '0003_work_pilot_salary_alter_users_work_users_sex_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, upload_to='friender_photo'),
        ),
    ]
